export const ActionTypes = {
    SET_AUTHENTICATE_TOKEN: 'SET_AUTHENTICATE_TOKEN',
    REMOVE_AUTHENTICATE_TOKEN: 'REMOVE_AUTHENTICATE_TOKEN',
    SET_USER: 'SET_USER',
    REMOVE_USER: 'REMOVE_USER',
};